version: 2
jobs:
  build:
    environment:
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy=in-process
    docker:
      - image: circleci/android:api-30

    steps:
      - checkout

      - run:
          name: Run checks
          command: ./gradlew clean test jacocoTestReport lint --continue --console=plain --max-workers=2 --no-daemon

      - store_artifacts:
          path: auth0/build/reports
          destination: reports

      - store_test_results:
          path: auth0/build/test-results

      - run:
          name: Upload Coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1
